'use strict';

const TokenErrorMessages = Object.freeze({
  MISSING_ACCESS_TOKEN: 'Access token is missing.',
  INVALID_AUTHORIZATION_FORMAT: 'Invalid authorization format.',
  UNAUTHORIZED_TOKEN_PROVIDED:
    'Access token provided was not generated by this service.',
  INVALID_TOKEN_METADTA: 'Access token provided was not formatted correctly.',
  TOKEN_EXPIRATION: 'Token has expired',
  AUTHENICATION_ERROR: 'Authenication Error.'
});

const EntitlementErrorMessages = Object.freeze({
  USER_UNAUTHORIZED: 'User not authorized to perform action.'
});

export { EntitlementErrorMessages, TokenErrorMessages };
