'use strict';

// Utility to freeze enums for immutability
const freezeEnum = obj => Object.freeze(obj);

const TokenErrorMessages = freezeEnum({
  MISSING_ACCESS_TOKEN: 'Access token is missing.',
  INVALID_AUTHORIZATION_FORMAT: 'Invalid authorization format.',
  UNAUTHORIZED_TOKEN_PROVIDED:
    'Access token provided was not generated by this service.',
  INVALID_TOKEN_METADATA: 'Access token provided was not formatted correctly.',
  TOKEN_EXPIRATION: 'Token has expired.',
  AUTHENTICATION_ERROR: 'Authentication Error.'
});

const EntitlementErrorMessages = freezeEnum({
  USER_UNAUTHORIZED: 'User not authorized to perform action.'
});

// Export enums and freeze utility
export { EntitlementErrorMessages, TokenErrorMessages, freezeEnum };
