'use strict';

const PERMISSONS = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  MANAGE_USERS: 'MANAGE_USERS',
  PROFILE_CREATE: 'PROFILE_CREATE',
  PROFILE_VIEW: 'PROFILE_VIEW',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  PROFILE_DELETE: 'PROFILE_DELETE',
  TASK_CREATE: 'TASK_CREATE',
  TASK_VIEW: 'TASK_VIEW',
  TASK_UPDATE: 'TASK_UPDATE'
};

export default PERMISSONS;
