'use strict';

const PERMISSONS = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  MANAGE_USERS: 'MANAGE_USERS',
  PROFILE_CREATE: 'PROFILE_CREATE',
  PROFILE_VIEW: 'PROFILE_VIEW',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  PROFILE_DELETE: 'PROFILE_DELETE',
  ACTIVITY_CREATE: 'ACTIVITY_CREATE',
  ACTIVITY_VIEW: 'ACTIVITY_VIEW',
  ACTIVITY_UPDATE: 'ACTIVITY_UPDATE',
  ACTIVITY_DELETE: 'ACTIVITY_DELETE'
};

export default PERMISSONS;
